# SITE CONFIGURATION
title: Nippotica
description: Deeptech Solutions, Real-World Impact.
url: "https://www.nippotica.com"

# SEO PLUGIN
social:
  name: Nippotica

# THEME SETTINGS
navigation:
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Privacy', link: '/privacy'}
  - {name: 'Contact', link: '/contact'}
  - {name: '会社情報', link: '/japanese'}

tagline: >
  「ディープテックの力を世界へ」 We turn research into market-ready ventures

hero_img: posts/nippotica_hero.webp

email: info@nippotica.com

service_worker: false

# BUILD SETTINGS
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

include: ['_pages']
permalink: /:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag